#!/bin/bash
PATH=$PATH:/sbin:/usr/local/sbin:/usr/local/bin
WORKING_DIR=$(cd $(dirname $0)/..; pwd)

. $WORKING_DIR/config/varnish.defaults
. $WORKING_DIR/config/util


[ -e $WORKING_DIR/config/environment ] && . $WORKING_DIR/config/environment
NOW=`date +%s`

error()
{
    echo 1>&2 "Failed to reload $VARNISH_VCL_CONF."
    exit 1
}

varnishadm -T "${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT}" \
  vcl.load reload$NOW $VARNISH_VCL_CONF || error
varnishadm -T "${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT}" \
  vcl.use reload$NOW || error
echo Current configs:
varnishadm -T "${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT}" vcl.list
